// SPDX-License-Identifier: Apache-2.0
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { Transaction } from '@vechain/sdk-core';
import { ThorClient } from '@vechain/sdk-network';
import { AdapterError } from './errors.js';
import { randomNonce } from './tx.js';

/** Result of a registry deployment. */
export interface DeployResult {
  contractAddress: string;
  txId: string;
}

/** Reads the compiled registry artifact (generated by the package build). */
export function registryBytecode(): string {
  const path = fileURLToPath(new URL('../artifacts/PassantRegistry.json', import.meta.url));
  const artifact = JSON.parse(readFileSync(path, 'utf8')) as { bytecode: string };
  return artifact.bytecode;
}

/**
 * Deploys the PassantRegistry contract, paid and signed by the given key
 * (on testnet, the sponsor doubles as deployer). Verifies the node's
 * genesis id first — a wrong node fails closed, it is never deployed to.
 * Safe to re-run: each run deploys a fresh, independent registry.
 */
export async function deployRegistry(
  nodeUrl: string,
  expectedGenesisId: string,
  deployerPrivateKey: Uint8Array,
): Promise<DeployResult> {
  const thor = ThorClient.at(nodeUrl);
  const genesis = await thor.blocks.getGenesisBlock();
  if (genesis === null || genesis.id.toLowerCase() !== expectedGenesisId.toLowerCase()) {
    throw new AdapterError(
      'NETWORK_MISMATCH',
      `node genesis ${genesis?.id ?? '(none)'} does not match the expected network`,
    );
  }
  const best = await thor.blocks.getBestBlockCompressed();
  if (best === null) {
    throw new AdapterError('SEND_FAILED', 'node returned no best block');
  }
  const baseFee = BigInt(best.baseFeePerGas ?? '0x0');
  const body = {
    chainTag: Number.parseInt(genesis.id.slice(-2), 16),
    blockRef: best.id.slice(0, 18),
    expiration: 32,
    clauses: [{ to: null, value: '0x0', data: registryBytecode() }],
    gas: 500000,
    maxFeePerGas: '0x' + (baseFee * 2n + 10n ** 11n).toString(16),
    maxPriorityFeePerGas: '0x' + (10n ** 11n).toString(16),
    dependsOn: null,
    nonce: randomNonce(),
  };
  const tx = Transaction.of(body).sign(deployerPrivateKey);
  const sent = await thor.transactions.sendTransaction(tx);
  const receipt = await thor.transactions.waitForTransaction(sent.id);
  if (receipt === null || receipt.reverted) {
    throw new AdapterError('SEND_FAILED', `deployment transaction ${sent.id} failed`);
  }
  const contractAddress = receipt.outputs[0]?.contractAddress;
  if (!contractAddress) {
    throw new AdapterError('SEND_FAILED', 'deployment receipt carries no contract address');
  }
  return { contractAddress, txId: sent.id };
}
